// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Footer Text field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text
   * - **API ID Path**: footer.footer_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_text: prismic.RichTextField;

  /**
   * LinkedIn Link field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: LinkedIn
   * - **API ID Path**: footer.linkedin_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin_link: prismic.LinkField;

  /**
   * GitHub Link field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: GitHub
   * - **API ID Path**: footer.github_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  github_link: prismic.LinkField;

  /**
   * Email field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Email
   * - **API ID Path**: footer.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  email: prismic.LinkField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomePageDocumentDataSlicesSlice = never;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Home Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.home_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  home_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

/**
 * Item in *Project → Project Topics*
 */
export interface ProjectDocumentDataProjectTopicsItem {
  /**
   * Topic field in *Project → Project Topics*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_topics[].topic
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  topic: prismic.RichTextField;
}

/**
 * Item in *Project → Project Content*
 */
export interface ProjectDocumentDataProjectContentItem {
  /**
   * Project Image field in *Project → Project Content*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_content[].project_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  project_image: prismic.ImageField<never>;

  /**
   * Project Subsection field in *Project → Project Content*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: Subsection
   * - **API ID Path**: project.project_content[].project_subsection
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_subsection: prismic.ContentRelationshipField<"project_subsection">;
}

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Project Title field in *Project*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Project
   * - **API ID Path**: project.project_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_title: prismic.TitleField;

  /**
   * Project Date field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Date
   * - **API ID Path**: project.project_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_date: prismic.RichTextField;

  /**
   * Project Topics field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_topics[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  project_topics: prismic.GroupField<
    Simplify<ProjectDocumentDataProjectTopicsItem>
  >;

  /**
   * Project Overview field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Overview
   * - **API ID Path**: project.project_overview
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_overview: prismic.RichTextField;

  /**
   * Project Preview Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_preview_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  project_preview_image: prismic.ImageField<never>;

  /**
   * Code Link field in *Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Code Link
   * - **API ID Path**: project.code_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  code_link: prismic.LinkField;

  /**
   * Demo Link field in *Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Demo Link
   * - **API ID Path**: project.demo_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  demo_link: prismic.LinkField;

  /**
   * Background Description field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Background Description
   * - **API ID Path**: project.background_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  background_description: prismic.RichTextField;

  /**
   * Technical Takeaway Description field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Takeaway Description
   * - **API ID Path**: project.technical_takeaway_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  technical_takeaway_description: prismic.RichTextField;

  /**
   * Project Content field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_content[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  project_content: prismic.GroupField<
    Simplify<ProjectDocumentDataProjectContentItem>
  >;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HomePageDocument
  | ProjectDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataProjectTopicsItem,
      ProjectDocumentDataProjectContentItem,
      AllDocumentTypes,
    };
  }
}
